sonar.projectKey=nguyentin05_cinema-booking
sonar.organization=nguyentin05
sonar.projectName=cinema-booking
sonar.sources=app
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.13
sonar.exclusions=app/__pycache__/**, mutants/**
sonar.coverage.exclusions=tests/**
sonar.python.ruff.reportPaths=ruff-report.json
sonar.sarifReportPaths=codeql-results/python.sarif