services:
  web:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-staging}
    container_name: web_app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5000:5000"
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - APP_ENV=staging
      - FLASK_HOST=0.0.0.0
      - SECRET_KEY=${SECRET_KEY}
      - MAX_BOOKING_SEAT_EACH_SHOWTIME=${MAX_BOOKING_SEAT_EACH_SHOWTIME}
      - BOOKING_EXPIRATION_TIME=${BOOKING_EXPIRATION_TIME}
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@host.docker.internal:3306/${MYSQL_DATABASE}
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=
      - STRIPE_PUBLIC_KEY=${STRIPE_PUBLIC_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe_cli
    command: listen --api-key ${STRIPE_SECRET_KEY} --forward-to http://web_app:5000/api/payment/stripe/callback
    restart: always
    depends_on:
      - web